version: '3.0'
services:
    bot:
        build: .
        container_name: bot
        restart: always
        stdin_open: true # docker run -i
        tty: true    # docker run -t
        # command: python /usr/src/app/bot.py
        volumes:
            - .:/usr/src/app
        env_file:
            - .env
        ports:
            - 41033:41033
